# 日志配置
logger:
  path: "logs" # 输出日志文件路径
  details:
    - type: 1 # 日志类型 0:打印所有级别 1:打印 DEBUG、INFO 级别 2:打印 WARN、ERROR、DPANIC、PANIC、FATAL 级别，默认0
      level: 0 # 日志打印级别 0:DEBUG 1:INFO 2:WARN 3:ERROR 4:DPANIC、5:PANIC、6:FATAL，默认0
      format: 0 # 输出日志格式 0:logfmt 1:json，默认0
      filename: "info.log" # 输出日志文件名称
      maxSize: 10 # 单个日志文件最多存储量（单位:MB）
      maxBackups: 10 # 日志备份文件最多数量
      maxAge: 7 # 日志保留时间（单位:天）
      compress: false # 是否压缩日志
      stdout: true # 是否输出到控制台
    - type: 2 # 日志类型 0:打印所有级别 1:打印 DEBUG、INFO 级别 2:打印 WARN、ERROR、DPANIC、PANIC、FATAL 级别，默认0
      level: 2 # 日志打印级别 0:DEBUG 1:INFO 2:WARN 3:ERROR 4:DPANIC、5:PANIC、6:FATAL，默认0
      format: 0 # 输出日志格式 0:logfmt 1:json，默认0
      filename: "error.log" # 输出日志文件名称
      maxSize: 10 # 单个日志文件最多存储量（单位:MB）
      maxBackups: 10 # 日志备份文件最多数量
      maxAge: 7 # 日志保留时间（单位:天）
      compress: false # 是否压缩日志
      stdout: true # 是否输出到控制台
